# -*- coding: utf-8 -*-
"""Customer Product Preference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ehe37OHy25CzM29HwdfmZxjL9da04x30
"""

import pandas as pd
data = {
    "Customer": ["C1","C2","C3","C4","C5"],
    "Product_A_Rating":[4,5,3,4,2],
    "Product_A_Importance":[5,4,4,3,3],
    "Product_B_Rating":[3,4,5,2,4],
    "Product_B_Importance":[4,5,5,3,4],
    "Product_C_Rating":[5,3,4,5,3],
    "Product_C_Importance":[5,3,4,4,3]
}
df = pd.DataFrame(data)
print(df)

#melt/ unpivote
long_df = df.melt(id_vars=["Customer"],
                  var_name="Product_Metric",
                  value_name="score")
long_df.head()

#split products + matric
long_df[["product","matric"]] = long_df["Product_Metric"].str.rsplit("_", n=1, expand=True)
long_df.head()

#create mapping for
matric_oder = {
    "Rating":1,
    "Importance":2
}
long_df["metric_order"] = long_df["matric"].map(matric_oder)

#Sort to preserve pair order
final_df = long_df.sort_values(["Customer","product","metric_order"])
long_df.head(20)

#generate insight
pivot = final_df.pivot_table(index="Customer",
                            columns="matric",
                            values="score",
                            aggfunc="mean")
pivot["gap"] = pivot["Importance"] - pivot["Rating"]
pivot

pivot.plot(kind="bar")